### ISSUE TITLE
Does this or can it support structlog logging?

### ISSUE THREAD

**Issue by james-certn** [adamchainz/flake8-logging#50]
### Description

Thank you for this, this is meaningful in the linting space!

I realize that this definitively defines that it supports Python standard logging. But _could_ it support structlog logging patterns? Would that be of interest?

To be clear, it's fine if the answer is no - I'm curious about this project's direction and potential scope.

**Comment by adamchainz** [comment]
For now the focus is on standard library logging. I’m pretty sure most of the issues don’t overlap with structlog but happy to take suggestions.

I’d prefer to make/use a second structlog focused plugin for structlog specific issues. I can’t remember much about it right now as I’m not using it on any current project.

**Comment by james-certn** [comment]
Thanks, appreciate the quick reply!
