### ISSUE TITLE
conda-forge version - Published

### ISSUE THREAD

**Issue by rxm7706** [adamchainz/flake8-logging#51]
### Description

@adamchainz 
Looking forward to trying this plugin. Thanks for the informative blog post too.
Just an FYI
I've added flake8-logging to conda-forge - available at
https://anaconda.org/conda-forge/flake8-logging - installable via
conda install -c conda-forge flake8-logging
Thanks & Regards.

**Comment by adamchainz** [comment]
Glad you enjoyed it and thanks for the heads up.
