### ISSUE TITLE
 detect injected logger instances

### ISSUE THREAD

**Issue by jkowalleck** [adamchainz/flake8-logging#86]
### Description

for some reason, issues on injected `Logger` instances are not properly found, despite the proper type hints are set.
"Injected" as in a (typed) function/method argument is used to transport an instance of `logging.Logger`. 
Based on the argument's type hint, it should be possible to run the functionality `flake8-logging` provides.

example:
```py
from logging import getLogger
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from logging import Logger


def do_something(logger: 'Logger') -> None:
    # expected a LOG012  << **NOT** thrown as expected ❌
    logger.debug('foo %s', 21, 22)


my_logger = getLogger(__name__)
# expected a LOG012  << thrown as expected ✔️
my_logger.debug('foo %s', 11, 12)

do_something(my_logger.getChild('something'))
```

**Comment by adamchainz** [comment]
As per #84, Flake8 plugins don’t look at type hints. They’re non-trivial to follow.

**Comment by adamchainz** [comment]
Closing because it’s unlikely we can do anything here.
